services:
  backend:
    image: arindamgb/request-inspector:backend-latest
    container_name: request-inspector-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 50M
    volumes:
          - /etc/timezone:/etc/timezone:ro
          - /etc/localtime:/etc/localtime:ro

  frontend:
    image: arindamgb/request-inspector:frontend-latest
    container_name: request-inspector-frontend
    ports:
      - "3000:80"
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./frontend/.env
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 20M
    volumes:
          - /etc/timezone:/etc/timezone:ro
          - /etc/localtime:/etc/localtime:ro
